### ISSUE TITLE
BAD GATEWAY for preflight requests

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/jsonrpc-filter#3]
![image](https://user-images.githubusercontent.com/9711879/57055875-4e5e0b80-6cd9-11e9-9bd8-cd832d5da513.png)

**Comment by sgkim126** [comment]
Thank you for report @joojis.
Would you use https://github.com/CodeChain-io/codechain-proxy until fixing it?
It works slightly different. The proxy rewrites the whole request to CodeChain node but this program forwards the request without modification to CodeChain node and adds `Access-Control-Allow-Origin` to the response.
I think this behavior change causes this error.
